name: chess-royale
services:
  db:
    image: postgres:17
    container_name: postgres_container
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: chessdb
    ports:
      - "5435:5432"

  redis:
    image: redis:7.4.1
    container_name: redis_container
    ports:
      - "6379:6379"
    

    

