name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install Dependencies
        run: |
          npm install -g pnpm@9.15.1
          pnpm install --frozen-lockfile


      - name: Build Project
        run: pnpm turbo build
