name: CD Pipeline - Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}    # Your EC2 instance IP or hostname
          username: ${{ secrets.EC2_USER }}  # Your SSH user (e.g., ubuntu)
          key: ${{ secrets.EC2_SSH_KEY }}    # The private key stored as a GitHub secret
          script: |
            cd /path/to/your/app
            git pull origin main
            npm install           # Or "pnpm install" if you're using pnpm
            npm run build         # Rebuild if necessary
            pm2 restart app       # Adjust this command to restart your service
